version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  json-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npx", "json-server", "--watch", "db.json", "--port", "3001"]
    volumes:
      - .:/app
    ports:
      - "3001:3001"
